from enum import Enum


class Messwertstatus(str, Enum):
    """
    Der Status eines Zählerstandes
    """

    ABGELESEN = "ABGELESEN"
    ERSATZWERT = "ERSATZWERT"
    ANGABE_FUER_LIEFERSCHEIN = "ANGABE_FUER_LIEFERSCHEIN"
    VORSCHLAGSWERT = "VORSCHLAGSWERT"
    NICHT_VERWENDBAR = "NICHT_VERWENDBAR"
    PROGNOSEWERT = "PROGNOSEWERT"
    VORLAEUFIGERWERT = "VORLAEUFIGERWERT"
    ENERGIEMENGESUMMIERT = "ENERGIEMENGESUMMIERT"
    FEHLT = "FEHLT"
