from enum import Enum


class Rechnungstyp(str, Enum):
    """
    Abbildung verschiedener Rechnungstypen zur Kennzeichnung von Rechnungen
    """

    ENDKUNDENRECHNUNG = "ENDKUNDENRECHNUNG"
    NETZNUTZUNGSRECHNUNG = "NETZNUTZUNGSRECHNUNG"
    MEHRMINDERMENGENRECHNUNG = "MEHRMINDERMENGENRECHNUNG"
    MESSSTELLENBETRIEBSRECHNUNG = "MESSSTELLENBETRIEBSRECHNUNG"
    BESCHAFFUNGSRECHNUNG = "BESCHAFFUNGSRECHNUNG"
    AUSGLEICHSENERGIERECHNUNG = "AUSGLEICHSENERGIERECHNUNG"
