from enum import Enum


class Zaehlertyp(str, Enum):
    """
    Bei diesem Enum handelt es sich um die Abbildung von Zählertypen der Sparten Strom und Gas.
    """

    DREHSTROMZAEHLER = "DREHSTROMZAEHLER"
    BALGENGASZAEHLER = "BALGENGASZAEHLER"
    DREHKOLBENZAEHLER = "DREHKOLBENZAEHLER"
    LEISTUNGSZAEHLER = "LEISTUNGSZAEHLER"
    MAXIMUMZAEHLER = "MAXIMUMZAEHLER"
    TURBINENRADGASZAEHLER = "TURBINENRADGASZAEHLER"
    ULTRASCHALLGASZAEHLER = "ULTRASCHALLGASZAEHLER"
    WECHSELSTROMZAEHLER = "WECHSELSTROMZAEHLER"
    MODERNE_MESSEINRICHTUNG = "MODERNE_MESSEINRICHTUNG"
    INTELLIGENTES_MESSSYSTEM = "INTELLIGENTES_MESSSYSTEM"
    ELEKTRONISCHER_ZAEHLER = "ELEKTRONISCHER_ZAEHLER"
    WIRBELGASZAEHLER = "WIRBELGASZAEHLER"
